### ISSUE TITLE
Writing stats for compaction jobs

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_server#455] opened 2022-01-03 08:47 UTC
Measure statistics for each compaction job (e.g. duration of compaction, no. of removed keys, etc)
[Parent task](https://github.com/atsign-foundation/at_server/issues/417)

**Comment by murali-shris** [comment] 2022-01-10 12:00
duplicate of https://github.com/atsign-foundation/at_server/issues/417

**Closed as completed by murali-shris** 2022-01-10 12:00 UTC
