### ISSUE TITLE
SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 6464

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#272] opened 2021-08-16 16:58 UTC
rather annoying bug that effects secondaries but we could not track down what caused it until now!..

Run a secondary with a value you want to pull and whilst the atLookUmpl is still connnected hit CNTL C.
As you hit control 

An uncaught exception happens...

```
import 'package:at_lookup/at_lookup.dart';

void main(List<String> args) async {
  print('Getting the value');
  await getMeter('hello').then((b) async {
    print(b);
  });
}

Future<List> getMeter(String j) async {
  var atLookUpImpl = AtLookupImpl(
    '@kryz_9850',
    'root.atsign.org',
    64,
    privateKey:
        'YOUR PKAM VALUE',
  );

  var value = [];
  value.add('hello');
  var a = await atLookUpImpl.llookup('public:custom_transmitterswr.wavi');
  print(a);
  value.add(a);
  return value;
}
```
What we see at the commandline

```
PS C:\Users\colin\GitHub\cconstab\meter\meter\lib\at_stuff> dart run .\getmeter.dart
getmeter.dart: Warning: Interpreting this as package URI, 'package:meter/at_stuff/getmeter.dart'.
Getting the value
INFO|2021-08-16 10:08:42.624521|AtLookup|auth success 

data:{"label":"SWR last updated Mon, 8/16/2021 10:08:00 AM","category":"TRANSMITTER","type":"Text","value":"1.548","valueLabel":""}
[hello, data:{"label":"SWR last updated Mon, 8/16/2021 10:08:00 AM","category":"TRANSMITTER","type":"Text","value":"1.548","valueLabel":""}]
^CTerminate batch job (Y/N)? y
PS C:\Users\colin\GitHub\cconstab\meter\meter\lib\at_stuff> 
```

The error we see in the console is 

```
main:stdout> FINER|2021-08-16 17:08:41.689619|Secondary_Util|result : {"label":"SWR last updated Mon, 8/16/2021 10:08:00 AM","category":"TRANSMITTER","type":"Text","value":"1.548","valueLabel":""} 
main:stdout> FINER|2021-08-16 17:08:41.689945|LocalLookupVerbHandler|Verb : llookup  Response: Response{_data: {"label":"SWR last updated Mon, 8/16/2021 10:08:00 AM","category":"TRANSMITTER","type":"Text","value":"1.548","valueLabel":""}, _type: null, _isError: false, _errorMessage: null} 
main:stdout> FINER|2021-08-16 17:08:41.690239|DefaultResponseHandler|Got response: Response{_data: {"label":"SWR last updated Mon, 8/16/2021 10:08:00 AM","category":"TRANSMITTER","type":"Text","value":"1.548","valueLabel":""}, _type: null, _isError: false, _errorMessage: null} 
main:stdout> SEVERE|2021-08-16 17:08:43.778790|InboundListener|SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 6464 
Paused at an unhandled exception (type 'continue' or [F7] to exit the isolate')
```

Plus the output from the debugger

```
void _startMicrotaskLoop() {
  _isInCallbackLoop = true;
  try {
    // Moved to separate function because try-finally prevents
    // good optimization.
    _microtaskLoop();
  } finally {
    _lastPriorityCallback = null;
    _isInCallbackLoop = false;
    if (_nextCallback != null) {
      _AsyncRun._scheduleImmediate(_startMicrotaskLoop);
    }
  }
```

    _AsyncRun._scheduleImmediate(_startMicrotaskLoop); is the line that gets marked red

**Comment by gkc** [comment] 2024-03-29 14:05
Duplicate of #1689

**Closed as completed by gkc** 2024-03-29 14:05 UTC
Labels: bug, P2
