### ISSUE TITLE
Better way do periodic jobs 

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_server#726] opened 2022-06-01 14:38 UTC
**Is your feature request related to a problem? Please describe.**
The way we start a periodic execution of stats is not in line with the way it is normally done

**Describe the solution you'd like**
Convert the job to the timer task

**Describe alternatives you've considered**
Cron can do the job too, how ever it is overkill as the scheduling requirements are very simple.

**Additional context**
The proposed code looks like this in the `schedule()` function of the class StatsNotificationService:

```dart
Timer.periodic(Duration(seconds: AtSecondaryConfig.statsNotificationJobTimeInterval), (timer) async {
    try {
      await writeStatsToMonitor();
    } on Exception catch (exception) {
      _logger.severe(
          'Exception occurred when writing stats ${exception.toString()}');
    } on Error catch(error) {
      _logger.severe(
          'Error occurred when writing stats ${error.toString()}');
    }
  });
```

**Comment by VJag** [comment] 2022-06-01 15:08
Sample code to understand the differences:

```dart
import 'dart:async';

main() async {
  Timer.periodic(Duration(seconds: 8), (timer) async {
    print('S');
    try {
      await getNumber();
    } on Exception catch (exception) {
      print(exception);
    } on Error catch(error) {
      print(error);
    }
    print('E');
  });

  // Not a proper async code
  while (true) {
    // Defencive code to prevent the stats job from exiting
    try {
      print('Start');
      await Future.delayed(
          Duration(seconds: 4),
          getNumber1);
      print('End');
    } on Exception catch (exception) {
      print(exception);
    }

  }
}

Future<int> getNumber() {
  //throw Error();
  return Future.value(10);
}

Future<int> getNumber1() {
  return Future.value(11);
}
```

**Comment by VJag** [comment] 2022-06-06 06:30
Also, analyze any scope to improve other schedulers.

**Comment by VJag** [comment] 2022-06-06 06:31
This issue might be one of the potential root causes for the stats notification scheduler not running.

**Comment by sitaram-kalluri** [comment] 2022-06-13 15:28
Duplicate of the [issue#720](https://github.com/atsign-foundation/at_server/issues/720)

**Closed as completed by sitaram-kalluri** 2022-06-13 15:28 UTC
Labels: enhancement
