### ISSUE TITLE
Server doesn't respond with @ prompt 

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#722] opened 2022-05-31 10:11 UTC
details:
https://github.com/atsign-foundation/at_server/issues/709#issuecomment-1137176257

**Comment by cconstab** [comment] 2022-05-31 16:33
This can happen when the secondary is "busy". The docker swarm answers the TCP socket then plugs through to the secondary, but the secondary is "busy" and does not give a prompt for a long time.

How the secondary gets busy and how we can know that is not easy..

**Comment by murali-shris** [comment] 2022-06-13 09:19
Root cause of the issue yet to be figured out.

**Comment by sitaram-kalluri** [comment] 2022-07-11 04:57
In local ran secondaries upto 30,000 commits and able to get the `@` prompt. Unable to reproduce the issue. Spent 2 SP in PR-40

**Comment by sitaram-kalluri** [comment] 2022-10-21 12:05
Observed the issue on the prod atsign : @visual61

Captured the below logs from the secondary server that might be useful for further debugging:

```
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 12:00:42.837294|AtSecondaryServer|Server cannot accept connections now. 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 12:00:50.752535|AtCertificationValidation|Waiting for total number of active connections to 0 or equal to number of monitor connections 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 12:00:50.752620|AtCertificationValidation|Total number of monitor connections are 0 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 12:00:50.752643|AtCertificationValidation|Total number of active connections are 1 
mailto:2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
```

<details>

<summary>Adding more logs:</summary>

```
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:52.495623|InboundListener|RCVD: [_22c704d2-c890-438a-9d93-f88f68a91c64] notify:id:9abfebe4-5242-402a-98cb-0f576ce1a73c:update:messageType:key:notifier:SYSTEM:ttln:900000:ttl:10000:ttr:-1:ccd:false:isEncrypted:true:sharedKeyEnc:XUXS6irIetf/B8IpWF9rDirPj6spGzCmFiWXV8UVTu1ggfxc0pe70O2zyF71q1PbE3MaGy/uv8DZ2omSP7m40HmTVdwtFcRjLkeVoLNTKxCUY4eGOOMRgifeHylqAKubWqOEthFsR4Sc5/5mbu2VAtrdzEjmgMkxNxhWxug3mSNq+lZkVYd40hvWRQYWcDhsSqA8hrGJ2Fj9DaNb/Ylm7bE0TV5dVoI5CdEnphb8+KD0r4E8HTbdw+FlwY41Pnevn7FTbbLb3CC7eR5AfRgb9u/wxe25yrISatTHBMKxI1XzJAAmNjT3Gd8Y/wNhlSvOXzPXuPnmW+X4xA0DKUAA8g==:pubKeyCS:4c58cbfceeba76aa9edb56fc26ef6fcc:@visual61:KRYZ.kryz_9850@kryz_9850:xusW7Gx6bbzs3UIELgf7htlrYQXSHs8m7HkMWaUUKkzPLBwuP0ORqfNsbSung1aXYQ4ZmUQaOmXMnOvvST2GOH5NpJQjnsBhru5837APcBR0t2lVbDtQ1yDR4woJaw+myN/6DSSelLq5HUHMVvXtoTIqVwK8hCFZnKSr4uO3s1ABsg3Q/9Z8pys6dv5WVMiDrX1Ko0tlJEZzdDStLZFFqrk3RdEzrsOpx+OKH/iYInaq3E/eZVui2ywrqRmKyml6tlm42MURHy/oPDX5rPiih+baIXxfEwhiRPWLAPB4IiU= 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:52.495786|NotifyVerbHandler|Storing the notification @visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:52.496120|NotifyVerbHandler|Cached cached:@visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:52.497398|InboundConnectionImpl|SENT: [_22c704d2-c890-438a-9d93-f88f68a91c64] data:success
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | @kryz_9850@ 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:53.292773|AtSecondaryServer|Server cannot accept connections now. 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:53.569303|InboundListener|RCVD: [_22c704d2-c890-438a-9d93-f88f68a91c64] notify:id:5b598355-fb55-4ad0-9a36-b5e121519784:update:messageType:key:notifier:SYSTEM:ttln:900000:ttl:10000:ttr:-1:ccd:false:isEncrypted:true:sharedKeyEnc:IqFyWNJWdMzgWLqdOTXZYq0Mm1ZJilefaC/aCwcKq1XuqZsZg8eZSkCv/TAy7pjTUVbrIX3B/AZBkcbLNhtP/Pj3o9ooi7GaIXcgAa5LdqcZeIkOkgWWE8hQp3szYyoPk/BVR2tMvRkkJUx75KH8RRrn5z7Mnlw3eHEJEOz24+UpGMwwdeQR/AYycUDa95o+9b63urii3eysWjmcift6junIy5yE0mr/D77w5rrtFa1YIPM/fi5NEb/N+aS0lohNnzKIbXhNkGU4jh/HU/8o4YdjOKzJYCthJcSIz/Afuz6F6+0+a87CX9RNP4BBYf28McZj9VQYrRw9oPmdEnVDZQ==:pubKeyCS:4c58cbfceeba76aa9edb56fc26ef6fcc:@visual61:KRYZ.kryz_9850@kryz_9850:xusW7Gx6bbzs3UIELgf7htlrYQXSHs8m7HkMWaUUKkzPLBwuP0ORqfNsbSung1aXYQ4ZmUQaOmXMnOvvST2GOH5NpJQjnsBhru5837APcBR0t2lVbDtQ1yDR4woJaw+myN/6DSSelLq5Hk7MVvXtoTIqVwK8hCFZnKSr4uO3s1ABsg3Q/9Z8pys6dv5WVMiDrX1Ko0tlJEZzdDStLZFFqrk3RdEzrsOpx+OKH/iYInaq3E/eZVui2ywrqRmKyml6tlm42MURHy/oPDT5rPiih+baIXxfEwhiRPWLAPB4IiU= 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:53.569489|NotifyVerbHandler|Storing the notification @visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:53.569824|NotifyVerbHandler|Cached cached:@visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:53.571236|InboundConnectionImpl|SENT: [_22c704d2-c890-438a-9d93-f88f68a91c64] data:success
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | @kryz_9850@ 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:54.664794|InboundListener|RCVD: [_22c704d2-c890-438a-9d93-f88f68a91c64] notify:id:8743de4a-7d18-426c-83fa-76dcf43d330d:update:messageType:key:notifier:SYSTEM:ttln:900000:ttl:10000:ttr:-1:ccd:false:isEncrypted:true:sharedKeyEnc:Vu9VPItQp1VriPo4bmFEYRhHWBpYl1FI5rT2CNza0E2nZgypUSxATlaCnPNoQqaYPwA8J3X24+AZV0ECneZTQiYn9RsfYfiL71vUY7BU5FPD1buemNBIJ47Gle83YUcNO2f9++LbvArCY/UZOkh6OMe+cQ+gzPkFic4OMct/X+vcvMnb/293Hza/txppvCjtDC7HNIhSX/U5QJx21rodKcWG4vn2M1edqJJQIRrqTXqwP6jd05RBOGjqAd6h7C1ycb9lzZ/BbA3dpemyck1Gd5uKtmdQiEh49HAyoFqeFwk6zCNfQotNag4FksWbzk/ju5Orc8YVGtQRLvlJvRi2NA==:pubKeyCS:4c58cbfceeba76aa9edb56fc26ef6fcc:@visual61:KRYZ.kryz_9850@kryz_9850:xusW7Gx6bbzs3UIELgf7htlrYQXSHs8m7HkMWaUUKkzPLBwuP0ORqfNsbSung1aXYQ4ZmUQaOmXMnOvvST2GOH5NpJQjnsBhru5837APcBV4tmlVbDtQ1yDR4woJaw+myN/6DSSelLq5HUHMVvXtoTIqVwK8hCFZnKSr4uO3s1ABsg3S/tZ8pys6dv5WVMiDrX1Ko0tlJEZzdDStLZFFqrk3RdEzrsOpx+OKH/iYInaq3E/eZVui2ywrqRmKyml6tlm42MURHy/oPDP5rPiih+baIXxfEwhiRPWLAPB4IiU= 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:54.664958|NotifyVerbHandler|Storing the notification @visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:54.665436|NotifyVerbHandler|Cached cached:@visual61:KRYZ.kryz_9850@kryz_9850 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:56:54.666717|InboundConnectionImpl|SENT: [_22c704d2-c890-438a-9d93-f88f68a91c64] data:success
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | @kryz_9850@ 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:00.729554|AtCertificationValidation|Waiting for total number of active connections to 0 or equal to number of monitor connections 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:00.729605|AtCertificationValidation|Total number of monitor connections are 0 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:00.729612|AtCertificationValidation|Total number of active connections are 1 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:10.730574|AtCertificationValidation|Waiting for total number of active connections to 0 or equal to number of monitor connections 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:10.730619|AtCertificationValidation|Total number of monitor connections are 0 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | INFO|2022-10-21 11:57:10.730626|AtCertificationValidation|Total number of active connections are 1 
2ffeca71-aaad-52d1-ba55-9173d5504f1f_secondary.1.sgeqiolx6ia0@swarm0002-13.us-central1-a.c.secondaries.internal    | 
```
</details>

**Comment by sitaram-kalluri** [comment] 2022-10-21 12:32
One of the potential causes of the issue is when a restart file is found by the secondary server, the secondary will restart.

However, if there are any active connections, the server waits for the active connection close before restarting. But will pause all the incoming connections. 

Code snippet from the at_certificate_validation.dart
```dart

    // The below line cause the server to not accept the incoming connections and not return '@' prompt
    AtSecondaryServerImpl.getInstance().pause();
    var isForceRestart = AtSecondaryConfig.isForceRestart!;
    if (isForceRestart) {
      logger.info('Initializing force restart on secondary server');
      _deleteRestartFile(filePath! + restartFile);
      await _restartServer();
      return;
    }
    var stopWaiting = false;
    var monitorSize = ConnectionUtil.getMonitorConnectionSize();
    logger.info(
        'Waiting for total number of active connections to 0 or equal to number of monitor connections');
    logger.info('Total number of monitor connections are $monitorSize');
    var totalSize = ConnectionUtil.getActiveConnectionSize();
    logger.info('Total number of active connections are $totalSize');
    if (totalSize == 0 || totalSize == monitorSize) {
      // Setting stopWaiting to true to prevent server start-up process into loop.
      stopWaiting = true;
      _deleteRestartFile(filePath! + restartFile);
      logger.severe('Certificates expired. Restarting secondary server');
      await _restartServer();
    }
```

**Comment by gkc** [comment] 2023-02-20 13:05
Fixed by https://github.com/atsign-foundation/at_server/pull/1131 which is in canary and will be promoted to all prod this week

**Closed as completed by gkc** 2023-02-20 13:05 UTC
Labels: bug, 3 SP, PR38, PR39, PR40
