### ISSUE TITLE
Unable to use update verb to create _ keys

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#219] opened 2021-07-15 00:53 UTC
**Describe the bug**
The scan verb does not show keys that start with the _ character. The update verb does not accept keys that start with the _ so hidden keys cannot be seen.

**To Reproduce**
1. Connect to secondary with openssl
2. authenticate with pkam:
3. Use the update: verb with a key starting with an _
4. See data -1 error essage

**Expected behavior**
_keys should be able to be created and updated using the update verb

**Screenshots**
```
cconstab@cally:~/@colin$ openssl s_client -ign_eof -brief ba46657d-227b-5ecf-ad16-161f80249772.hornet.atsign.zone:2489
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = ba46657d-227b-5ecf-ad16-161f80249772.hornet.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@scan
data:["location.wavi@realisticforeign","locationnickname.wavi@realisticforeign","publickey@realisticforeign","signing_publickey@realisticforeign","weather@realisticforeign"]
@from:@realisticforeign
data:_e8defea5-d893-4a22-851f-db249e87a485@realisticforeign:110c8842-b061-43c7-9f94-8f91fc626391
@pkam:GkzZ8/z7H8NZdPIqQAVWf/o3fG+H3KnapXlQwe1IVSBXsoqIyWugSj0odOZfFIq84ADOgZW9UDdmTOLvXXqjg4X4/WtDGZTzgMGmYl7NXNR6otkbWDoPW6e3vX/ly7tmh47MiuEQVScjgGRw0Dtum5geWjKGt1o2GVMqRWzZVF7BjUhKCwSn6vnq/ecmAy4d12W+XBV70p937EioZtUzEpn+l8p7sSWcvV5pwcWNHRCVAY1uz6DiKeik6Rc7OUJbUJSxMPhUMMwywVDitUXnO/xw6mVCYkhHrHl13kDm6jSvMSEWTKvBw6zG044ZbsN71sV+0mMvBXbfxFw2l/SX7g==
data:success
@realisticforeign@scan
data:["@realisticforeign:signing_privatekey@realisticforeign","cached:public:_notlisted@realisticforeign","cached:public:email@tigerequivalent","public:location.wavi@realisticforeign","public:locationnickname.wavi@realisticforeign","public:publickey@realisticforeign","public:signing_publickey@realisticforeign","public:weather@realisticforeign"]
@realisticforeign@update:public:_listed@realisticforeign sunny
data:-1
@realisticforeign@update:public:slisted@realisticforeign sunny
data:11
@realisticforeign@update:public:_plop@realisticforeign sunny
data:-1
@realisticforeign@update:public:s_plop@realisticforeign sunny
data:12
@realisticforeign@scan
data:["@realisticforeign:signing_privatekey@realisticforeign","cached:public:_notlisted@realisticforeign","cached:public:email@tigerequivalent","public:location.wavi@realisticforeign","public:locationnickname.wavi@realisticforeign","public:publickey@realisticforeign","public:s_plop@realisticforeign","public:signing_publickey@realisticforeign","public:slisted@realisticforeign","public:weather@realisticforeign"]
@realisticforeign@
```

**Comment by sitaram-kalluri** [comment] 2021-07-15 10:31
Update of keys starting with an "_" will not have a commitID by design and they will not be part of the scan. We have to know the exact key name to look up a key starting with "_". 

Listing this cached "_" key is a problem "cached:public:_notlisted@realisticforeign". This issue is fixed in the following PR: https://github.com/atsign-foundation/at_server/issues/218

Dev testing notes:
-------------------------
@sitaram@update:public:_testkey@sitaram testValue
data:-1
@sitaram@plookup:_testkey@sitaram
data:testValue
@sitaram@update:public:_testkey@sitaram privateKeyValue
data:-1
@sitaram@plookup:_testkey@sitaram
data:privateKeyValue
@sitaram@

**Closed as completed** 2021-07-26 15:28 UTC
Labels: bug, 1 SP, blocker
