### ISSUE TITLE
TLS connections from secondary fail (e.g connecting to root) This is only in the wtf/dess_env environments

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#152] opened 2021-05-29 23:11 UTC
**Describe the bug**
Secondary cannot make TLS connection out to root 

**To Reproduce**
1. Connected to secondary using openssl
2. Authenticated with PKAM
3. Issued scan verb for another secondary
4. Error message no answers
5. Looked in log files for secondary and included logs

**Expected behavior**
Scan to work along with connections to root and other secondaries

**Log Files**
```
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:01:54.008729|PkamVerbHandler|pkam auth:true
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:01:54.008791|PkamVerbHandler|Verb : pkam  Response: Response{_data: success, _type: null, _isError: false, _errorMessage: null}
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:01:54.008826|DefaultResponseHandler|Got response: Response{_data: success, _type: null, _isError: false, _errorMessage: null}
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:02:01.923522|InboundListener|command received: scan:@stage sessionID:_00b42eb7-d88f-4971-bb6e-1c64af45eb79
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:02:01.923617|AtSecondaryServer|inside _executeVerbCallBack: scan:@stage
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:02:01.923676|DefaultVerbExecutor|verb handler found : ScanVerbHandler
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | FINER|2021-05-29 23:02:01.923898|AtLookup|AtLookup.findSecondary received atsign: @stage
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | SEVERE|2021-05-29 23:02:02.081169|AtLookup|AtLookup.findSecondary connection to root.atsign.wtf exception: HandshakeException: Handshake error in client (OS Error:
dess_secondary.1.licb62g99d7d@localhost    |    CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:359))
dess_secondary.1.licb62g99d7d@localhost    |
dess_secondary.1.licb62g99d7d@localhost    | SEVERE|2021-05-29 23:02:02.081299|OutboundClient|secondary server not found for @stage: Instance of 'SecondaryNotFoundException'
dess_secondary.1.licb62g99d7d@localhost    |
```

**Were you using an @application when the bug was found?**
  - [Command line

**Additional context**
Session from the openssl side

```
cconstab@cally:~$ openssl s_client -ign_eof effectivechamois.shaduf.com:8891
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = effectivechamois.shaduf.com
verify return:1
---
Certificate chain
 0 s:CN = effectivechamois.shaduf.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFOjCCBCKgAwIBAgISBC/vNOPvPLO9jhwRdBUnSh72MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA1MjIxNzQ2NTlaFw0yMTA4MjAxNzQ2NTlaMCYxJDAiBgNVBAMT
G2VmZmVjdGl2ZWNoYW1vaXMuc2hhZHVmLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMN/Uuwi8E1Fb0dbEI45gfj9CRP+31iv4c2te4tqZAfz5BpP
1no3GorvJaa8aKPJokn2BGClvO1ZxvM1wwWwBl+Lizj6ekqrX8gEicOmK56gSAMo
xp9QN22uSwXPA2lC1CnV/ag9MYveeFapbPqwb3GqYYniaCYApCHw9I6RR/tDrVii
vC/Gu1Udke9G8gWA9fC5x42oCz8m/r/egkHwyDFe9Wq5iWUUlwKgC5J5T1XXCB7C
5CMJoBCgiPrj5+loWWdZ3POApUpwAKoDyfeCD6UzVgImAG0R1nsANLwaySM5YJnL
TJv/kSMUtOHg2AebUCS/fzcjUhuUInUAIZlLYQ0CAwEAAaOCAlQwggJQMA4GA1Ud
DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
AQH/BAIwADAdBgNVHQ4EFgQUn2lLrgadInEsMJiHvCXYOMjChgUwHwYDVR0jBBgw
FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbZWZmZWN0aXZlY2hhbW9pcy5zaGFk
dWYuY29tMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAgYKKwYBBAHW
eQIEAgSB8wSB8ADuAHUAlCC8Ho7VjWyIcx+CiyIsDdHaTV5sT5Q9YdtOL1hNosIA
AAF5lWblegAABAMARjBEAiAHddGLyJ2yit7pQ5Do9IVI4fBc1UOt8olvNHJbpdXg
MwIgQTSr/RN9kDPfYyelIK85UnLG3muB6X9UiMAAOSRt77kAdQD2XJQv0XcwIhRU
GAgwlFaO400TGTO/3wwvIAvMTvFk4wAAAXmVZuWAAAAEAwBGMEQCIErlmXGDtfsJ
3Q3yW+AGyFuwcDTNY5NhK1AIcnwX5oTMAiBCAATmSfc/4N5hPP3fmKd0r8eAMxXd
4G7BMAMATp1SyzANBgkqhkiG9w0BAQsFAAOCAQEAWhwcmTx5OJwFPsfGmDnNVd+R
RlZTgA45PMm4kUC78LT7llkePqNiFPR0o113CYozrQMjUeCE+UGYjTmwPnLFsz1r
YlYzJg5YFNo2GXhHcmujvaIN0K+qTS6Ryl2+mVCTq77EsxJ2iR+z4NiRD9MG70BD
lt2hm+9+hP/3Hnq6xDU2W5tSihButrI2gQivA41URcg6lPLk6PMW8emMzVYa7ROo
ka9+tDV1qmqnOMVOhspSqWTkKLi7bYyD9HrbLD5wQhg/SjnsEbbNJif3abt6M3tH
G+plQU8PmStk5vhZSQxN8sszIs5vrGl9KC9UvDATlP7ygJDfF1Iiml85Dqal/w==
-----END CERTIFICATE-----
subject=CN = effectivechamois.shaduf.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA5                                                                                                                         12:RSA+SHA512:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-P                                                                                                                         SS+SHA512:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4559 bytes and written 429 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 2654FE7BA64470B3A4EF851903C6580E694842F5B0570E4A4AA3FC03D9974A39
    Session-ID-ctx:
    Resumption PSK: 4300D1663A17B4609AE6C33253F8DB0B4B26F46D998B847CE4011F210354B6B2B78C3FB390EF1DB7CBD38E7A9B1A49BD
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 172800 (seconds)
    TLS session ticket:
    0000 - 7c 1b 33 eb 28 7e 18 33-a8 a2 9e d3 72 0c d1 1b   |.3.(~.3....r...
    0010 - e5 90 fe 33 b0 d1 9b f7-b1 a9 c0 93 7b 39 06 15   ...3........{9..
    0020 - ac 86 17 bc 4e 87 1a de-1c d3 c3 74 a5 cf db 40   ....N......t...@
    0030 - 42 a0 fc 3a 3d f8 a0 29-0d 5b 71 b4 12 61 80 c8   B..:=..).[q..a..
    0040 - 35 b5 f9 ff 8f ff 1e 0c-61 b2 12 c9 de 6f 61 3e   5.......a....oa>
    0050 - 81 d4 87 d2 9a 85 cd ae-d6 9e aa 08 fb b2 25 bc   ..............%.
    0060 - 82 5a ba 2b dd 78 2a 53-26 43 e4 1b 58 09 31 78   .Z.+.x*S&C..X.1x
    0070 - e3 2c f0 85 ee 3b 87 a3-1f 24 47 ff 43 4c 59 28   .,...;...$G.CLY(
    0080 - f8 77 b6 cc fb d9 68 33-b7 c6 26 35 67 53 bc 40   .w....h3..&5gS.@
    0090 - b5 de e0 1b cf c7 55 9b-43 7e 76 c9 8d 93 23 1d   ......U.C~v...#.
    00a0 - fc e5 b7 37 21 1a 8b c9-dd 65 6d 91 81 0f 9d ab   ...7!....em.....

    Start Time: 1622329234
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: D4FC4168288B890849A89B5C9A64C3D74C64992F9A1A05DACC054FE2EE9A3CDE
    Session-ID-ctx:
    Resumption PSK: 51FCAD5046EFBCC80F25CDD2E519AAFE3FD45FCE06A0D0B347E1ACC48DCE5BBA06E4E295B5090B6C8A9E01AE7654F075
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 172800 (seconds)
    TLS session ticket:
    0000 - 7c 1b 33 eb 28 7e 18 33-a8 a2 9e d3 72 0c d1 1b   |.3.(~.3....r...
    0010 - 5c 22 7c 29 1c 78 9f fc-fd ef 8e b7 19 c7 d8 43   \"|).x.........C
    0020 - bc 33 8d 07 56 ab 74 1f-17 b7 9d 84 81 bb eb 44   .3..V.t........D
    0030 - 7a 0b c0 66 63 d0 4d a5-ee ae 83 bc 11 df 0e dc   z..fc.M.........
    0040 - e0 3a d6 92 af 18 8a 9e-44 23 a3 5d 9d 97 ba 25   .:......D#.]...%
    0050 - c0 65 da 79 0b 29 99 d0-99 75 5d 4b f2 b5 2e b5   .e.y.)...u]K....
    0060 - 90 38 99 fe 08 4a c8 81-ff e4 98 ac 48 ed b9 cb   .8...J......H...
    0070 - c9 f5 bb 53 88 25 f8 2c-f7 35 7a 15 bc 39 1e b0   ...S.%.,.5z..9..
    0080 - db 73 5a e1 da 05 0d f2-67 de 8e 32 0f b0 f3 22   .sZ.....g..2..."
    0090 - 1d 3f 4a dd 01 df 8b 69-57 bb bd 5f 1c 8e 81 0a   .?J....iW.._....
    00a0 - 65 9e 4f 7d 77 d3 6c 2c-1f c7 f8 52 d6 84 da 02   e.O}w.l,...R....

    Start Time: 1622329234
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
@from:@dess
data:_00b42eb7-d88f-4971-bb6e-1c64af45eb79@dess:7ddd2d31-fddc-4bde-8ee2-a44ccfe6fa68
@pkam:HmQh5LDY52nK1hHBySvJvCUkuaHGf40ExS0bwWLLSdwJHuPZdnIC22XujUKfkd1XaBAGJae4tFOic6bKzPESBJTH03MSWIMij/vra7q/XdT8wgtJ+QUT                                                                                                                         z3PtSpw3B3gSyO1WEEPkc1ohFE1LIj+NggeXu0NIX4Ggu294bmpNyboGnXPN7UG4VhuGgj//C3vKabqhq2OCAZmGGSilWDpY3MsUUpVWt1H0ENmRWez02qvKHR                                                                                                                         G0sNgRn+pELHeqPmC+eWsrCD2Fv6nZdMfAtyr6QByHn+ZIlqaaLs5k1yl5A4zNvOMvkq2+GVJ2b13rg0W0Fp6kOYYlhvAtPgxczA2rFg==
data:success
@dess@scan:@stage
error:AT0007-Secondary server not found : No secondary url found for atsign: @stage
@dess@scan:@crusher_stage
error:AT0007-Secondary server not found : No secondary url found for atsign: @crusher_stage
@dess@
```

**Comment by cpswan** [comment] 2021-05-30 03:30
When were the root.atsign.wtf certs last updated?

**Comment by cpswan** [comment] 2021-05-30 10:09
@cconstab can you confirm whether the secondaries on the dev_env swarm are also doing this?

Also how is time synced on your dess system?

I think to get this properly reproduced (and part of ongoing tests) we're going to need to use dess, starting with me following in your footsteps.

**Comment by cconstab** [comment] 2021-05-30 14:56
My dess system on ionos.com is time synched by ntp. The wtf environment was still being updated yesterday by shepherd but I will relook today. I strongly suspect the same issue as we are back to the original state and I saw this problem on both dess and wtf.

Root cert I checked on Friday and it has I think 60days or so left so it's fine.

Thin builds are tough to fault find! Certs fail on

Time  ... NTP
DNS. .... It's failing so DNS must be working to connect
CAroot ... It's there but is it being used or found ?
Openssl ... Missing a/some libraries?
Anything else ?

So close!

**Comment by cpswan** [comment] 2021-05-30 17:28
I think we should roll back dev_env again until this is fixed, and remove it from the present automation, so I'll do that on Docker Hub, and PR to follow.

Do we have a dependency on Openssl? That's not what's in the slim build - just system libs and CA certs (which should be enough for Dart apps using Dart's TLS implementation.

I can see ISRG_Root_X1.crt in /usr/share/ca-certificates/ca-certificates on the thin build.

Curiously I see no sign whatsoever of ca-certificates in the dev_env_47 image (the last one we built with Ubuntu). I wonder if we might be better off not having ca-certificates on the filesystem, as Dart has them anyway in [dart-lang/root-certificates](https://github.com/dart-lang/root_certificates)

```
This directory contains the root CA certificates chosen to be trusted by
Mozilla's NSS library, reformatted into an array in C source code, to be
used by the default SecurityContext obect in Dart's dart:io library for
secure networking (TLS, SSL) for operating systems that don't have a supported
certificate store.
```

We're back to where we were a few weeks ago (before the thin build was declared good) - we need a comprehensive test environment before we can get confidence in the thin build (or any other changes), and dess should be that. So let's get to a working dess, and then we can start shoving experiments into it.

**Comment by cpswan** [comment] 2021-06-01 11:23
Also the certs we get from ZeroSSL are signed by a chain to USERTrust RSA Certification Authority, but that also is clearly there in the runimage ca-certificates (and the Dart root certs).

**Comment by cpswan** [comment] 2021-06-04 14:45
The TLS issues should be fixed by #165 

But... I'm now seeing `HandShakeException` when I `scan:@dess` or `scan:@stage` - @cconstab I'd value your thoughts on what could cause that?

This MAY be happening because of an issue with #160 causing bad images that by now could be running on all the staging secondaries.

Logs:

```
INFO|2021-06-04 14:32:18.116195|AtSecondaryServer|currentAtSign : @sudokusufficient

FINER|2021-06-04 14:32:18.118487|CommitLogKeyStore|last committed sequence: 3

FINEST|2021-06-04 14:32:18.122659|HivePersistenceManager|scheduleKeyExpireTask starting cron job.

FINEST|2021-06-04 14:32:18.123466|AtRefreshJob|scheduleKeyRefreshTask runs at 11 hours

INFO|2021-06-04 14:32:28.142160|AtSecondaryServer|Secondary server started on version : 1.0.0+DEV

INFO|2021-06-04 14:32:28.142194|AtSecondaryServer|Secure Socket open for @sudokusufficient !

FINER|2021-06-04 14:32:28.142220|AtSecondaryServer|serverSocket _listen : SecureServerSocket

FINER|2021-06-04 14:32:33.328252|AtSecondaryServer|In _listen - clientSocket.peerCertificate : null

FINER|2021-06-04 14:32:44.650905|InboundListener|command received: from:@sudokusufficient sessionID:_d48ad622-7145-48fa-b303-ba3da98853d5

FINER|2021-06-04 14:32:44.650942|AtSecondaryServer|inside _executeVerbCallBack: from:@sudokusufficient

FINER|2021-06-04 14:32:44.650969|DefaultVerbExecutor|verb handler found : FromVerbHandler

FINER|2021-06-04 14:32:44.651983|FromVerbHandler|fromAtSign : @sudokusufficient currentAtSign : @sudokusufficient

FINER|2021-06-04 14:32:44.652244|FromVerbHandler|Verb : from  Response: Response{_data: data:_d48ad622-7145-48fa-b303-ba3da98853d5@sudokusufficient:c6b6d395-1e2b-40aa-b26a-4e90d0c1cf01, _type: null, _isError: false, _errorMessage: null}

FINER|2021-06-04 14:32:44.652309|FromResponseHandler|Got response: Response{_data: data:_d48ad622-7145-48fa-b303-ba3da98853d5@sudokusufficient:c6b6d395-1e2b-40aa-b26a-4e90d0c1cf01, _type: null, _isError: false, _errorMessage: null}

FINER|2021-06-04 14:33:12.902867|InboundListener|command received: pkam:MrOu+Uumcu9y4vvTkMowc7AJwQigF4QFMQT7nfuAm4PAbjolmCuR62u/ISvappeVKrTYbdEPSeWKbbsAl++LcnmTM62Ec+HE593XFr+CQB25epAHEk1+CF7EYfZeG+yM9mTTMBFH528wbc896ghE99+Yd5EkiuG2Z+kC7WZrMv+HVxsn0R/FI4gz3O2C5z1N5X/BB1zlQXBqvSz10mDTEa1//fE24VNfTO4z2ohc548Osop7CdTiA8PgkdnTh5wZisJb4Q9FSCTVsWX61Rt3drVdaVorcx8yP4ZqKgZCl4xSSRBkIr+7pcvbyMy5ESMx/HWZoMUG2MI2Dz9vwPXrhw== sessionID:_d48ad622-7145-48fa-b303-ba3da98853d5

FINER|2021-06-04 14:33:12.902920|AtSecondaryServer|inside _executeVerbCallBack: pkam:MrOu+Uumcu9y4vvTkMowc7AJwQigF4QFMQT7nfuAm4PAbjolmCuR62u/ISvappeVKrTYbdEPSeWKbbsAl++LcnmTM62Ec+HE593XFr+CQB25epAHEk1+CF7EYfZeG+yM9mTTMBFH528wbc896ghE99+Yd5EkiuG2Z+kC7WZrMv+HVxsn0R/FI4gz3O2C5z1N5X/BB1zlQXBqvSz10mDTEa1//fE24VNfTO4z2ohc548Osop7CdTiA8PgkdnTh5wZisJb4Q9FSCTVsWX61Rt3drVdaVorcx8yP4ZqKgZCl4xSSRBkIr+7pcvbyMy5ESMx/HWZoMUG2MI2Dz9vwPXrhw==

FINER|2021-06-04 14:33:12.902962|DefaultVerbExecutor|verb handler found : PkamVerbHandler

FINER|2021-06-04 14:33:12.905255|PkamVerbHandler|pkam auth:true

FINER|2021-06-04 14:33:12.905273|PkamVerbHandler|Verb : pkam  Response: Response{_data: success, _type: null, _isError: false, _errorMessage: null}

FINER|2021-06-04 14:33:12.905320|DefaultResponseHandler|Got response: Response{_data: success, _type: null, _isError: false, _errorMessage: null}

FINER|2021-06-04 14:33:19.030541|InboundListener|command received: scan:@dess sessionID:_d48ad622-7145-48fa-b303-ba3da98853d5

FINER|2021-06-04 14:33:19.030570|AtSecondaryServer|inside _executeVerbCallBack: scan:@dess

FINER|2021-06-04 14:33:19.030611|DefaultVerbExecutor|verb handler found : ScanVerbHandler

FINER|2021-06-04 14:33:19.030824|AtLookup|AtLookup.findSecondary received atsign: @dess

FINER|2021-06-04 14:33:19.738512|AtLookup|AtLookup.findSecondary got answer: effectivechamois.shaduf.com:8891 and closing connection

INFO|2021-06-04 14:33:25.327485|OutboundClient|fromResult :

FINER|2021-06-04 14:33:25.327874|OutboundConnectionImpl|InternetAddress('216.250.126.215', IPv4):8891 Disconnected

SEVERE|2021-06-04 14:33:25.327956|OutboundClient|HandShakeException for @dess: Instance of 'HandShakeException'

SEVERE|2021-06-04 14:33:25.328015|AtSecondaryServer|Instance of 'HandShakeException'

FINER|2021-06-04 14:35:40.572970|InboundListener|command received: scan:@stage sessionID:_d48ad622-7145-48fa-b303-ba3da98853d5

FINER|2021-06-04 14:35:40.573020|AtSecondaryServer|inside _executeVerbCallBack: scan:@stage

FINER|2021-06-04 14:35:40.573087|DefaultVerbExecutor|verb handler found : ScanVerbHandler

FINER|2021-06-04 14:35:40.573423|AtLookup|AtLookup.findSecondary received atsign: @stage

FINER|2021-06-04 14:35:41.172506|AtLookup|AtLookup.findSecondary got answer: 91085c77-9c2b-5874-bcad-b3a520d408d9.buzz.do-sf2.atsign.zone:2400 and closing connection

INFO|2021-06-04 14:35:50.538460|OutboundClient|fromResult : null

FINER|2021-06-04 14:35:50.538802|OutboundConnectionImpl|InternetAddress('167.99.103.237', IPv4):2400 Disconnected

SEVERE|2021-06-04 14:35:50.538867|OutboundClient|HandShakeException for @stage: Instance of 'HandShakeException'

SEVERE|2021-06-04 14:35:50.538906|AtSecondaryServer|Instance of 'HandShakeException'
```

Tails end of `openssl s_client` session:

```
@from:@sudokusufficient
data:_d48ad622-7145-48fa-b303-ba3da98853d5@sudokusufficient:c6b6d395-1e2b-40aa-b26a-4e90d0c1cf01
@pkam:MrOu+Uumcu9y4vvTkMowc7AJwQigF4QFMQT7nfuAm4PAbjolmCuR62u/ISvappeVKrTYbdEPSeWKbbsAl++LcnmTM62Ec+HE593XFr+CQB25epAHEk1+CF7EYfZeG+yM9mTTMBFH528wbc896ghE99+Yd5EkiuG2Z+kC7WZrMv+HVxsn0R/FI4gz3O2C5z1N5X/BB1zlQXBqvSz10mDTEa1//fE24VNfTO4z2ohc548Osop7CdTiA8PgkdnTh5wZisJb4Q9FSCTVsWX61Rt3drVdaVorcx8yP4ZqKgZCl4xSSRBkIr+7pcvbyMy5ESMx/HWZoMUG2MI2Dz9vwPXrhw==
data:success
@sudokusufficient@scan:@dess
error:AT0008-Handshake failure : Instance of 'HandShakeException'
@sudokusufficient@scan:@stage
error:AT0008-Handshake failure : Instance of 'HandShakeException'
@sudokusufficient@
```

**Closed as completed** 2021-06-04 15:58 UTC
Labels: bug
